project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!practice*.qmd"

website:
  title: "CHJR 2023"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Getting started"
        url: index.qmd
      - section: "Lessons"
        contents:
          - lesson-day1-01-intro.qmd
          - lesson-day1-02-clean.qmd
          - lesson-day2-01-analysis.qmd
          - lesson-day3-01-wrangling.qmd
          - lesson-day4-01-visualizing.qmd
          - lesson-monthly1-review.qmd
      - section: "Solutions"
        contents:
          - solution-day1-clean.qmd
          - solution-day2-analysis.qmd
          - solution-day3-wrangling.qmd
          - solution-day4-visualizing.qmd
          - solution-monthly1-review.qmd
      - section: "Resources"
        contents:
          - resources/functions.qmd
          - resources/projects.qmd
          - resources/keyboard-shortcuts.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged



